pipeline{
 agent any
    
    stages {
        stage('build') {
            steps {
                script{
                  dir('Desktop'){
                    dir('test'){
                      dir ('frontend'){
                        sh "docker build -t registry.deploy.flipr.co.in/frontend:latest ."
                      }
                      dir ('backend'){
                        sh "docker build -t registry.deploy.flipr.co.in/backend:latest ."
                      }
                    }
                  }
                }
            }
        }
        stage("deploy"){
          steps{
            script{
                sh "docker images"
            }
          }
        }
    }
}
