pipeline{
 agent any
    
    stages {
        stage('build') {
            steps {
                script{
                  sh " pwd "
                  sh " ls "
                }
            }
        }
        // stage("deploy"){
          
        // }
    }
}
