pipeline{
 agent any

  environment{
   REG_CRED = credentials("reg_cred")
  }
    
    stages {
        stage('build') {
            steps {
                script{
                  dir('Desktop'){
                    dir('test'){
                      dir ('frontend'){
                        sh "docker build -t registry.deploy.flipr.co.in/frontend:latest ."
                      }
                      dir ('backend'){
                        sh "docker build -t registry.deploy.flipr.co.in/backend:latest ."
                      }
                    }
                  }
                }
            }
        }
        stage("push to registry"){
          steps{
            script{
                sh "echo $REG_CRED_PSW | docker login registry.deploy.flipr.co.in -u $REG_CRED_USR --password-stdin"
                sh "docker push registry.deploy.flipr.co.in/frontend:latest"
                sh "docker push registry.deploy.flipr.co.in/backend:latest"

            }
          }
        }
    }
}
